<?php

namespace AppBundle\Repository;

/**
 * AmmoTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmmoTypeRepository extends \Doctrine\ORM\EntityRepository
{
    public function getByName($label)
    {
        $qb = $this->findOneBy(
            [
                'label' => $label,
            ]
        );

        return $qb->getQuery()->getResult();
    }
}
