<?php

namespace AppBundle\Repository;

/**
 * RarityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RarityRepository extends \Doctrine\ORM\EntityRepository
{
}
